spring:
  profiles: 
  
  
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
    
  redis:
    host: redis-17393.c12.us-east-1-4.ec2.cloud.redislabs.com
    port: 17393
    password: aQmmc5nwmffRF8wW
    database: 0

#  rabbitmq: 
#    addresses: localhost
#    username: guest
#    password: guest
#    virtual-host: / 

  rabbitmq: 
    addresses: clam.rmq.cloudamqp.com
    username: oayqpgfa
    password: DpC_x7SJH7-U0DbrZ8BWBcncmNLwHT9R
    virtual-host: oayqpgfa
  
server:
  port: 1104
  ssl:
    enabled: false

logging:
  level:
    com.bot.ws: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /home/pi/Documents/u-bot-client/logs/u-bot-client.log
      
app:
  properties:
    u-bot-exchange-name: ubot.server.exchange
    uBotQueue: ubot-queue
    speechHost: speech.googleapis.com
    speechPort: 443
    recorderSampleRate: 16000
    bytesPerSample: 2
    oAuth2Scopes:
      - https://www.googleapis.com/auth/cloud-platform
    apiAiAuthToken: 0e9ad4acbd6c433baa8a5cbb5d878661
    awsAccessKey: AKIAIQCUVMP7NGWDYEEQ
    awsSecretKey: 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
    awsPollyVoiceId: Joanna
    accountSid: AC76af38cf591d437e45d5fd7b246f9d83
    authToken: c92e3eec1a6f8137aab6216b7a2b0bdd
    spotifyClientId: 948876007d6c449a942fe1ac492e765e
    spotifyClientSecret: 0af81bd988bf42cd93bb1196b00ab0f6
    mopidyWebSocketUrl: ws://localhost:6680/mopidy/ws/


intentTypeList:
  ignoreIntents: smalltalk
    
  musicIntents:
    music.play: PLAY
    music_player_control.play: PLAY
    music_player_control.pause: PAUSE
    music_player_control.resume: RESUME
    music_player_control.stop: STOP
    music_player_control.skip_forward: NEXT
    music_player_control.skip_backward: PREVIOUS
    music_player_control.shuffle: SHUFFLE
    music_player_control.add_favorite: ADD_FAVORITE
    music_player_control.add_playlist: ADD_PLAYLIST
    