info:
  build:
    artifact: bot-chat-server-ws
    name: bot-chat-server-ws
    description: bot-chat-server-ws
    version: '@project.version@'

management:
  port: 31122
  security:
    enabled: false

server:
  port: 11122
  
security:
  user:
    password: null
  basic:
    enabled: false
 
spring:

#  rabbitmq: 
#    addresses: localhost
#    username: guest
#    password: guest
#    virtual-host: /  

  rabbitmq: 
    addresses: <address>
    username: <username>
    password: <password>
    virtual-host: <v-host>
  
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
    
  redis:
    host: <host>
    port: <port>
    password: <password>
    database: 0
 
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.englishasl: DEBUG 

app:
  version: v1
  
  properties:
    twilioUrl: url
    accountSid: <account-sid>
    authToken: <auth-token>
    chatExchangeName: ubot.server.exchange
    oAuth2Scopes:
      - https://www.googleapis.com/auth/cse
