info:
  build:
    artifact: bot-chat-server-ws
    name: bot-chat-server-ws
    description: bot-chat-server-ws
    version: '@project.version@'

management:
  port: 31122
  security:
    enabled: false

server:
  port: 11122
  
security:
  user:
    password: null
  basic:
    enabled: false
 
spring:

#  rabbitmq: 
#    addresses: localhost
#    username: guest
#    password: guest
#    virtual-host: /  

  rabbitmq: 
    addresses: clam.rmq.cloudamqp.com
    username: oayqpgfa
    password: DpC_x7SJH7-U0DbrZ8BWBcncmNLwHT9R
    virtual-host: oayqpgfa
  
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
    
  redis:
    host: redis-17393.c12.us-east-1-4.ec2.cloud.redislabs.com
    port: 17393
    password: aQmmc5nwmffRF8wW
    database: 0
 
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.englishasl: DEBUG 

app:
  properties:
    twilioUrl: url
    accountSid: AC76af38cf591d437e45d5fd7b246f9d83
    authToken: c92e3eec1a6f8137aab6216b7a2b0bdd
    chatExchangeName: ubot.server.exchange
    oAuth2Scopes:
      - https://www.googleapis.com/auth/cse